### ISSUE TITLE
devcontainer를 이용하여 개발환경 세팅하기

### ISSUE THREAD

**Issue by gyunseo** [hell-of-sloth/skkubot#14]
- 일관된 개발 환경을 구성합니다.
- <https://code.visualstudio.com/docs/devcontainers/containers>
- Windows에서는 Docker Desktop과 WSL2를 이용하여 손 쉽게 구성할 수 있습니다.
- MacOS에서는 Docker Desktop 혹은 orbstack을 이용하여 구성할 수 있습니다.

**Comment by jnnkk** [comment]
멋있어요
